name: mobile_nurtura
description: "A new Flutter project."
publish_to: 'none'
 
version: 1.0.0+1
 
environment:
  sdk: ^3.10.8
 
dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8
  fl_chart: ^0.68.0
  http: ^1.6.0
  shared_preferences: ^2.5.5
  image_picker: ^1.0.7
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
 
flutter:
  uses-material-design: true
 
  assets:
    - assets/images/logo_nurtura.png
    - assets/images/logo_bg_nurtura.png
 
  fonts:
    - family: Gloock
      fonts:
        - asset: assets/fonts/Gloock-Regular.ttf
 
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
 